### ISSUE TITLE
Shop command

### ISSUE THREAD

**Issue by Kibishan** [Discord-Bros/Economy-Discord-Bot-example#1]
I am a noob at coding so can you add a custom shop command ?

(Sorry for english i am french)

**Comment by Nekobu1** [comment]
hey can you Dm me neko#6323

**Comment by Nekobu1** [comment]
i will send me the quick.db economy code

**Comment by Kibishan** [comment]
Ok i add you (my name is infini)

**Comment by Nekobu1** [comment]
hey my id change to neko#0003 sorry i changed it

**Comment by Kibishan** [comment]
ok :)
